// category
export const GET_CATEGORY = "GET_CATEGORY";
export const FAILED_GET_CATEGORY = "FAILED_GET_CATEGORY";

// sort
export const GET_BY_QUERY_CATEGORY = "GET_BY_QUERY_CATEGORY";
export const FAILED_GET_BY_QUERY_CATEGORY = "FAILED_GET_BY_QUERY_CATEGORY";
export const REMOVE_GET_BY_QUERY_CATEGORY = "REMOVE_GET_BY_QUERY_CATEGORY";
