// category
export const GET_CATEGORY = "GET_CATEGORY";
export const FAILED_GET_CATEGORY = "FAILED_GET_CATEGORY";

// sort
export const GET_CATALOG = "GET_ATALOG";
export const FAILED_GET_CATALOG = "FAILED_GET_CATALOG";
export const REMOVE_GET_CATALOG = "REMOVE_GET_CATALOG";
