export const START_FEEDBACK = "START_FEEDBACK";
export const SUCCESS_FEEDBACK = "SUCCESS_FEEDBACK";
export const FAILED_FEEDBACK = "FAILED_FEEDBACK";
export const REMOVE_FEEDBACK = "REMOVE_FEEDBACK";
