// get new product
export const GET_NEW_PRODUCT = "GET_NEW_PRODUCT";
export const FAILED_GET_NEW_PRODUCT = "FAILED_GET_NEW_PRODUCT";

// all
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const FAILED_GET_ALL_PRODUCT = "FAILED_GET_ALL_PRODUCT";

// historu
export const GET_HISTORY_PRODUCT = "GET_HISTORY_PRODUCT";
export const FAILED_GET_HISTORY_PRODUCT = "FAILED_GET_HISTORY_PRODUCT";

// detail
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const FAILED_GET_DETAIL_PRODUCT = "FAILED_GET_DETAIL_PRODUCT";
export const REMOVE_DETAIL_PRODUCT = "REMOVE_DETAIL_PRODUCT";

// query
export const GET_BY_SORT_PRODUCT = "GET_BY_SORT_PRODUCT";
export const FAILED_GET_BY_SORT_PRODUCT = "FAILED_GET_BY_SORT_PRODUCT";
