//get
export const GET_PRODUCT = "GET_PRODUCT";
export const FAILED_GET_PRODUCT = "FAILED_GET_PRODUCT";

//remove
export const START_REMOVE_PRODUCT = "START_REMOVE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const FAILED_REMOVE_PRODUCT = "FAILED_REMOVE_PRODUCT";

// add
export const START_ADD_PRODUCT = "START_ADD_PRODUCT";
export const SUCCESS_ADD_PRODUCT = "SUCCESS_ADD_PRODUCT";
export const FAILED_ADD_PRODUCT = "FAILED_ADD_PRODUCT";

// detail
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const FAILED_GET_DETAIL_PRODUCT = "FAILED_GET_DETAIL_PRODUCT";

// update
export const START_UPDATE_PRODUCT = "START_UPDATE_PRODUCT";
export const SUCCESS_UPDATE_PRODUCT = "SUCCESS_UPDATE_PRODUCT";
export const FAILED_UPDATE_PRODUCT = "FAILED_UPDATE_PRODUCT";

// featured product
export const SUCCESS_FEATURED_PRODUCT = "SUCCESS_FEATURED_PRODUCT";
export const FAILED_FEATURED_PRODUCT = "FAILED_FEATURED_PRODUCT";
