//get
export const GET_PRODUCT = "GET_PRODUCT";
export const FAILED_GET_PRODUCT = "FAILED_GET_PRODUCT";

//remove
export const START_REMOVE_PRODUCT = "START_REMOVE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const FAILED_REMOVE_PRODUCT = "FAILED_REMOVE_PRODUCT";

// add
export const START_ADD_PRODUCT = "START_ADD_PRODUCT";
export const SUCCESS_ADD_PRODUCT = "SUCCESS_ADD_PRODUCT";
export const FAILED_ADD_PRODUCT = "FAILED_ADD_PRODUCT";

// detail
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const FAILED_GET_DETAIL_PRODUCT = "FAILED_GET_DETAIL_PRODUCT";
