// category
export const GET_CATEGORY = "GET_CATEGORY";
export const FAILED_GET_CATEGORY = "FAILED_GET_CATEGORY";
// add category
export const START_ADD_CATEGORY = "START_ADD_CATEGORY";
export const SUCCESS_ADD_CATEGORY = "SUCCESS_ADD_CATEGORY";
export const FAILED_ADD_CATEGORY = "FAILED_ADD_CATEGORY";
// add catalog
export const START_ADD_CATALOG = "START_ADD_CATALOG";
export const SUCCESS_ADD_CATALOG = "SUCCESS_ADD_CATALOG";
export const FAILED_ADD_CATALOG = "FAILED_ADD_CATALOG";
// remove catalog
export const START_REMOVE_CATALOG = "START_REMOVE_CATALOG";
export const REMOVE_CATALOG = "REMOVE_CATALOG";
export const FAILED_REMOVE_CATALOG = "FAILED_REMOVE_CATALOG";

// detail catalog
export const GET_DETAIL_CATALOG = "GET_DETAIL_CATALOG";
export const FAILED_GET_DETAIL_CATALOG = "FAILED_GET_DETAIL_CATALOG";
