// login
export const START_LOGIN = "START_LOGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAILED_LOGIN = "FAILED_LOGIN";

// log out
export const START_LOGOUT = "START_LOGOUT";
export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";
export const FAILED_LOGOUT = "FAILED_LOGOUT";

// register
export const START_REGISTRATION = "START_REGISTRATION";
export const SUCCESS_REGISTRATION = "SUCCESS_REGISTRATION";
export const FAILED_REGISTRATION = "FAILED_REGISTRATION";
export const REMOVE_MESSAGE_REGISTER = "REMOVE_MESSAGE_REGISTER";

// forget
export const START_FORGET = "START_FORGET";
export const SUCCESS_FORGET = "SUCCESS_FORGET";
export const FAILED_FORGET = "FAILED_FORGET";

// exp forget
export const GET_TOKEN = "GET_TOKEN";
export const FAILED_GET_TOKEN = "FAILED_GET_TOKEN";

// forget
export const START_RESET = "START_RESET";
export const SUCCESS_RESET = "SUCCESS_RESET";
export const FAILED_RESET = "FAILED_RESET";

// user
export const GET_USER = "GET_USER";
export const FAILED_USER = "FAILED_USER";

//get products
export const GET_PRODUCT_DASHBOARD = "GET_PRODUCT_DASHBOARD";
export const FAILED_GET_PRODUCT_DASHBOARD = "FAILED_GET_PRODUCT_DASHBOARD";
//remove products
export const START_REMOVE_PRODUCT_DASHBOARD = "START_REMOVE_PRODUCT_DASHBOARD";
export const REMOVE_PRODUCT_DASHBOARD = "REMOVE_PRODUCT_DASHBOARD";
export const FAILED_REMOVE_PRODUCT_DASHBOARD =
  "FAILED_REMOVE_PRODUCT_DASHBOARD";
// add product
export const START_ADD_PRODUCT = "START_ADD_PRODUCT";
export const SUCCESS_ADD_PRODUCT = "SUCCESS_ADD_PRODUCT";
export const FAILED_ADD_PRODUCT = "FAILED_ADD_PRODUCT";
// detail product
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const FAILED_GET_DETAIL_PRODUCT = "FAILED_GET_DETAIL_PRODUCT";

// feedback
export const START_FEEDBACK = "START_FEEDBACK";
export const SUCCESS_FEEDBACK = "SUCCESS_FEEDBACK";
export const FAILED_FEEDBACK = "FAILED_FEEDBACK";
export const REMOVE_FEEDBACK = "REMOVE_FEEDBACK";

// category
export const GET_CATEGORY = "GET_CATEGORY";
export const FAILED_GET_CATEGORY = "FAILED_GET_CATEGORY";
// add category
export const START_ADD_CATEGORY = "START_ADD_CATEGORY";
export const SUCCESS_ADD_CATEGORY = "SUCCESS_ADD_CATEGORY";
export const FAILED_ADD_CATEGORY = "FAILED_ADD_CATEGORY";
// add catalog
export const START_ADD_CATALOG = "START_ADD_CATALOG";
export const SUCCESS_ADD_CATALOG = "SUCCESS_ADD_CATALOG";
export const FAILED_ADD_CATALOG = "FAILED_ADD_CATALOG";
